name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.9.0
  drift_dev: ^2.29.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
